name: build SUKISU
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Prepare timezone 
      run: |
            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y-%H%M")" >> $GITHUB_ENV
            sudo rm /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          
    - name: Fetch Clang
      run: |  
           mkdir clang && wget "$(curl -s https://raw.githubusercontent.com/ZyCromerZ/Clang/main/Clang-main-link.txt)" -O "zyc-clang.tar.gz" -RLO && tar -C clang/ -xf zyc-clang.tar.gz
           git clone https://github.com/greenforce-project/gcc-arm64 -b main --depth=1 gcc64
           git clone https://github.com/greenforce-project/gcc-arm -b main --depth=1 gcc32
     
    - name: Fetch SUKISU
      run: |
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
           
    - name: Clean previous build
      run: |
           make clean && make mrproper
                 
    - name: Build Kernell
      run: |
           export ARCH=arm64
           export PATH="${PWD}/clang/bin:${PWD}gcc64/bin:${PWD}gcc32/bin:$PATH"  
           export KBUILD_BUILD_USER=Mahiro
           export KBUILD_BUILD_HOST=HiraTeam
           export KBUILD_COMPILER_STRING="${PWD}/clang"
           make O=out ARCH=arm64 surya_defconfig  
           make -j$(nproc --all) O=out \ ARCH=arm64 \ LLVM=1 \ LLVM_IAS=1 \ CLANG_TRIPLE=aarch64-linux-gnu- \ CROSS_COMPILE=aarch64-linux-gnu- \ CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \ CROSS_COMPILE_ARM32=arm-linux-gnueabi-
           mv out/.config out/surya_defconfig.txt
           
    - name: Upload defconfig 
      uses: actions/upload-artifact@v4
      with:
        name: surya_defconfig-${{ env.BUILD_TIME }}
        path: out/surya_defconfig.txt
      
    - name: Fetch AnyKernel3
      run: |
           git clone --depth=1 https://github.com/rinnsakaguchi/AnyKernel3.git -b FSociety AnyKernel3  
           if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
           fi
           if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
           fi           
           if [ -f out/arch/arm64/boot/dtb.img ]; then
            cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
           fi
        
    - name: Upload Kernel 
      uses: actions/upload-artifact@v4
      with:
        name: Lucifer-Kernel-Surya-${{ env.BUILD_TIME }}
        path: AnyKernel3/*
